import type { Metadata } from "next";
import { Header } from "@/components/header";
import "../shared/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="antialiased">
        <Header />
        <div className="px-[16px] flex flex-col overflow-hidden xl:overflow-visible">
          {children}
        </div>
      </body>
    </html>
  );
}
